name: Deploy React Application

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Extract repository name only
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Use repository name in a subsequent step
        run: echo "The repository name is $REPO_NAME"

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 18
          cache: "npm"

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm install axios postcss autoprefixer

      - name: Verify Axios installation
        run: npm list axios

      - name: Build
        run: npm run build -- --base=/$REPO_NAME

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5